### ISSUE TITLE
BMP header size generated by Page.bitmap() is misaligned.

### ISSUE THREAD

**Issue by fryasu** [hayasix/xdwlib#1]
Thanks for great valuable XDW library!

We want to get the page image, not as file.

Though using Page.bitmap() method, error is caused when parsing the generated BMP data by Pillow library.

The reproduction code is below:

```python
import io
import PIL
import xdwlib

with xdwlib.xdwopen("test.xdw", readonly=True) as doc:
    page = doc.page(0)
    bmp = page.bitmap()
    im = PIL.Image.open(io.BytesIO(bmp.octet_stream()))
    im.save("test.png")
```

Raised error is the below.

```
Traceback (most recent call last):
  File "C:....test.py", line 11, in <module>
    im.save("test.png")
  File "C:....\PIL\Image.py", line 2178, in save
    self._ensure_mutable()
  File "C:....\PIL\Image.py", line 597, in _ensure_mutable
    self._copy()
  File "C:....\PIL\Image.py", line 590, in _copy
    self.load()
  File "C:....\PIL\ImageFile.py", line 247, in load
    raise OSError(
OSError: image file is truncated (29762 bytes not processed)
```

There seems a problem with the alignment of the C structure in BitmapFileHeader (bitmap.py).

I tried to make small patch, and would be glad if I could contribute something.
[xdwlib.bitmap-fixed.patch.gz](https://github.com/hayasix/xdwlib/files/8349136/xdwlib.bitmap-fixed.patch.gz)

Regards,

**Comment by hayasix** [comment]
Thanks fryasu, I'll check it later.  It seems to be a potential bug in Win32 and has appeared in Win64.  Your workaround is helpful.

**Comment by hayasix** [comment]
I added `_pack_ = 1` before every `_field_ = ...`, and updated xdwlib on PyPI.  Thanks a lot.

**Comment by fryasu** [comment]
I confirmed works fine.

Thank you for quick response!
