### ISSUE TITLE
直線の色を変えられない

### ISSUE THREAD

**Issue by shin1007** [hayasix/xdwlib#3]
直線(STRAIGHTLINE)のborder_colorをgetまたはsetする際にKeyError(15615)が発生してしまいます。
RECTANGLEでは問題なくできています。

もしかしたらDocuWorks側の問題かもしれません。

環境:
xdwlib==3.8.5.1　から　xdwlib==3.10.2　まで。（それ以前のものはインストールに問題があり試していません）
DocuWorks 9.0.11

**Comment by hayasix** [comment]
xdwlib 3.10.3 で修正しました。ご指摘ありがとうございました。

**Comment by shin1007** [comment]
こちらでも動作確認しました。
解決していただき、ありがとうございます。助かりました！
