### ISSUE TITLE
バインダーのbitmap取得について

### ISSUE THREAD

**Issue by marimox-net** [hayasix/xdwlib#4]
複数の文書が含まれているバインダーでbinder.page(n).bitmap()を行うと、出力予定の文書より前に存在する別文書のページ数分、インデックスがずれます。

具体的には、A文書1ページ、B文書10ページが存在するバインダーで
binder.page(1).bitmap()やbinder.document(1).page(0).bitmap()で取得できる画像データがA文書の1ページ目になります。
またbinder.page(-1).bitmap()で最終ページを取得しようとすると、B文書の9ページ目が取得されます。

ライブラリバージョン:xdwlib==3.10.3

**Comment by hayasix** [comment]
page.py の def bitmap() の最後で self.pos + 1 としているところを self.absolute_page() + 1 としたらいいような気がします。近いうちに調べてみましょう。

**Comment by marimox-net** [comment]
self.absolute_page() + 1に変更することにより問題なく動作しました。
迅速なご返答ありがとうございます。

**Comment by hayasix** [comment]
よかった :-)
ご指摘ありがとうございました。
