### ISSUE TITLE
xdwfile.protectについて

### ISSUE THREAD

**Issue by nemui0119** [hayasix/xdwlib#5]
xdwfileモジュールのprotect関数についてです。
実行時に「name 'XDW_PROTECT_256' is not defined」というエラーが発生しています。

xdwapiモジュールの491行目に「XDW_PROTECT_PSWD256 = 7」とありますので、
xdwfileモジュールの248行目にある「XDW_PROTECT_256」が誤記ではないでしょうか。

お手数おかけしますがご確認よろしくお願いいたします。

環境は以下のとおりです。
xdwlib == 3.10.4
DocuWorks 8.0.14

**Comment by hayasix** [comment]
確かに誤記のようです。ちょっと今 Windows が使えない状況なのでテストできませんが、お手数ですがお手元で XDW_PROTECT_PSWD256 へ修正してみていただけますか。

**Comment by nemui0119** [comment]
修正したところ動作しました。
お手数ですが、次にアップデートされる際に反映いただけますと幸いです。
こちらのライブラリ、非常に役立っております。ありがとうございます。

**Comment by hayasix** [comment]
確認いただきありがとうございました。
Windows が使えるようになりましたら修正改版します。

**Comment by nemui0119** [comment]
3.10.5でのご対応ありがとうございました。
クローズします。
