### ISSUE TITLE
PW等設定不要時のxdwfile.protectについて

### ISSUE THREAD

**Issue by nemui0119** [hayasix/xdwlib#6]
xdwfileモジュールのprotect関数でprotect_typeを'PASSWORD', 'PASSWORD128', 'PASSWORD256'のいずれかとし、
本関数optionを以下のようにPW等無しとして設定する場合について確認させてください。
・password = ""
・fullaccess = ""
・comment = ""

このとき、以下のエラーが発生します。
TypeError: expected bytes, str found

文字列をバイト列に変更すべきかと思い、各設定を以下のようにしてみましたが、その場合も上記のエラーが発生しました。
・password = "".encode()

つきましては、xdwfile.pyの253〜255行を以下のように修正いただけないでしょうか(手許で修正してみたところ、期待通りの挙動となりました)。
opt.szOpenPswd = o("password") or b""
opt.szFullAccessPswd = o("fullaccess") or b""
opt.lpszComment = o("comment") or b""

#5とは別件となりますので新規にIssue作成しております。
よろしくお願いいたします。

xdwlib == 3.10.5
DocuWorks 8.0.14

**Comment by hayasix** [comment]
すみません、見落としですね。たぶん Python2 のときから誰も使わなかったのだと思います。
で、次のような修正はどうでしょう? パスワードは bytes より str で書けた方がいいのではと。
```diff --git a/xdwlib/xdwfile.py b/xdwlib/xdwfile.py
index 95c77ed..ac0c646 100644
--- a/xdwlib/xdwfile.py
+++ b/xdwlib/xdwfile.py
@@ -250,9 +250,10 @@ def protect(input_path,
                         XDW_PROTECT_PSWD256):
         opt = XDW_SECURITY_OPTION_PSWD()
         opt.nPermission = flagvalue(XDW_PERM, o("permission"), store=True)
-        opt.szOpenPswd = o("password") or ""
-        opt.szFullAccessPswd = o("fullaccess") or ""
-        opt.lpszComment = o("comment") or ""
+        opt.szOpenPswd = (o("password") or "").encode()
+        opt.szFullAccessPswd = (o("fullaccess") or "").encode()
+        encoding = "utf-8" if protect_type == XDW_PROTECT_PSWD256 else "ascii"
+        opt.lpszComment = (o("comment") or "").encode(encoding)
     elif protect_type in (XDW_PROTECT_PKI, XDW_PROTECT_PKI256):
         opt = XDW_SECURITY_OPTION_PKI()
         opt.nPermission = flagvalue(XDW_PERM, o("permission"), store=True)
```

**Comment by nemui0119** [comment]
ご回答ありがとうございます。
また、ニッチな機能ばかり多用してしまいすみません……。

確かにstrで書けた方がありがたいです！
お手数おかけしますが、ご提案の内容で修正いただけますと幸いです。

**Comment by hayasix** [comment]
上記変更で更新しました。ありがとうございました。

**Comment by hayasix** [comment]
クローズします。
